export const FATCH_USERS_REQUEST_DETAILS = 'FATCH_USERS_REQUEST_DETAILS'
export const FATCH_USERS_SUCCESS_DETAILS = 'FATCH_USERS_SUCCESS_DETAILS'
export const FATCH_USERS_FAILURE_DETAILS = 'FATCH_USERS_FAILURE_DETAILS'