export const FATCH_USERS_REQUEST_POPULER = 'FATCH_USERS_REQUEST_POPULER'
export const FATCH_USERS_SUCCESS_POPULER = 'FATCH_USERS_SUCCESS_POPULER'
export const FATCH_USERS_FAILURE_POPULER = 'FATCH_USERS_FAILURE_POPULER'